add fake data
CA-G12/GeekSchool pull request #17
Opened 2022-10-13 13:57 UTC by mahmoudhammad309

related to #10

2022-10-13 20:04 UTC, Raghad-Mezied requested changes

2022-10-13 20:04 UTC, Raghad-Mezied commented on server/database/seed/assignment_student_teacher.json
> +{"id":3,"student_id":3,"assignment_id":3,"is_submitted":false,"grades":3,"material_link":"https://digg.com/proin.xml?curae=eu&donec=nibh&pharetra=quisque&magna=id&vestibulum=justo&aliquet=sit&ultrice
Just rename this file to be in camelCase and all similar files. 
Also, let this file be just `assigmentStudent` (without  `teacher`)

2022-10-14 08:36 UTC, moustf approved these changes

2022-10-14 12:54 UTC, Bas-Shiekh approved these changes

2022-10-14 21:00 UTC, Aaya-Elsharief approved these changes

2022-10-16 06:20 UTC, Raghad-Mezied approved these changes

2022-10-16 06:20 UTC, merged