23 create signup page
CA-G12/GeekSchool pull request #39
Opened 2022-10-16 21:31 UTC by Bas-Shiekh

2022-10-17 06:20 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-17 20:42 UTC, Raghad-Mezied requested changes

2022-10-17 20:42 UTC, Raghad-Mezied commented on client/src/pages/signUp/SignUp.tsx
> +  const inputValue = (e: React.ChangeEvent<HTMLInputElement>): void => {
Always choose a name that expresses its type, if it's a function choose an action name. when I read `inputValue` I automatically think it's a value(string).

2022-10-17 20:42 UTC, Raghad-Mezied commented on client/src/pages/signUp/SignUp.tsx
> +    }
We send a message in the back (msg), with axios, you can access it through `err.response.data.msg`

2022-10-19 08:17 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-19 08:17 UTC, mahmoudhammad309 approved these changes

2022-10-20 04:19 UTC, moustf commented on client/src/pages/signUp/index.tsx
> +import "antd/dist/antd.min.css";
Importing the CSS file of Antd goes in the local CSS file, not in the JSX file.

2022-10-20 04:21 UTC, moustf commented on client/src/pages/signUp/style.css
> +
Import the fonts and create the colors variables inside either the index.css or app.css file, in order for all the components to use them and to DRY our code.

2022-10-20 04:30 UTC, moustf commented on client/src/pages/signUp/style.css
> +}
Try to import the fonts and create the colors variables inside either index.css or app.css, in order for  all the components to use them and DRY our code.

2022-10-20 04:32 UTC, moustf commented on client/src/components/signUpForm/ParentSignUp.tsx
> +  const regex = /^\w+([\\.-]?\w+)*@\w+([\\.-]?\w+)*(\.\w{2,3})+$/;
It will be good if you explained what the regex does in a comment for later times during the project.

2022-10-20 04:33 UTC, moustf requested changes
Just two little things and we are good to go.

2022-10-20 08:44 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-20 08:46 UTC, mahmoudhammad309 submitted a review, later dismissed

2022-10-21 18:49 UTC, moustf submitted a review, later dismissed

2022-10-24 09:37 UTC, moustf approved these changes

2022-10-24 09:39 UTC, Raghad-Mezied approved these changes

2022-10-24 12:10 UTC, mahmoudhammad309 approved these changes

2022-10-24 12:52 UTC, merged