[GET] class/classId/announcment
CA-G12/GeekSchool pull request #50
Opened 2022-10-17 08:39 UTC by mahmoudhammad309

create a middle-ware for students and teacher
related to #31

2022-10-17 18:37 UTC, Raghad-Mezied requested changes

2022-10-17 18:37 UTC, Raghad-Mezied commented on server/controllers/class/getAnnouncement.ts
> +};
what if an error happens in getAnnouncementQuery? Add your code in try and catch so you can catch the error.

2022-10-17 18:37 UTC, Raghad-Mezied commented on server/routes/class.ts
> +// classRouter.get('/class/:classId/announcement', getAnnouncement);
Remove the commented lines

2022-10-17 18:37 UTC, Raghad-Mezied commented on server/routes/class.ts
> +classRouter.get('/class/:classId/announcement', userAuth, studentAndTeacher, getAnnouncement);
Test your route

2022-10-18 13:17 UTC, moustf approved these changes

2022-10-18 13:19 UTC, Raghad-Mezied approved these changes

2022-10-18 13:19 UTC, Aaya-Elsharief approved these changes

2022-10-18 13:20 UTC, Bas-Shiekh approved these changes

2022-10-18 13:20 UTC, merged