49 create login route
CA-G12/GeekSchool pull request #59
Opened 2022-10-17 11:51 UTC by Bas-Shiekh

2022-10-17 11:59 UTC, Aaya-Elsharief approved these changes

2022-10-17 18:08 UTC, Raghad-Mezied requested changes

2022-10-17 18:08 UTC, Raghad-Mezied commented on server/controllers/auth/login.ts
> +    res.json({ msg: err });
Here just pass the error to the next error middleware and it will be handled there

2022-10-18 16:27 UTC, Raghad-Mezied commented on server/controllers/auth/login.ts
> +    await generateToken({ id: rows[0].getDataValue('id'), username: rows[0].getDataValue('name'), role: rows[0].getDataValue('role') });
Rename username to name

2022-10-18 16:27 UTC, Raghad-Mezied approved these changes

2022-10-18 17:06 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-18 17:32 UTC, moustf commented on server/utils/jwt/index.ts
> +
Why did you create the generateToken function, the singToken function does the same purpose!

2022-10-18 17:34 UTC, moustf commented on server/routes/auth.ts
> +authRouter.post('/login', login);
Let the path be '/auth/login' to follow the convention.

2022-10-18 17:37 UTC, moustf approved these changes

2022-10-18 19:20 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-19 06:30 UTC, Aaya-Elsharief approved these changes

2022-10-19 06:32 UTC, moustf approved these changes

2022-10-20 06:23 UTC, Raghad-Mezied approved these changes

2022-10-20 06:24 UTC, merged