Created the class statistics route.
CA-G12/GeekSchool pull request #65
Opened 2022-10-18 19:44 UTC by moustf

- Pushed the pulled main during the development.
- Added the /api/v1/class/:classId/statistics route logic and tests.
- Edited the fake seed data to let sequelize generate the ids by himself.
- Refactored some tests and the signup controller.
- Resolve conflicts.

2022-10-19 13:19 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-20 07:44 UTC, mahmoudhammad309 requested changes
Why use postgres queries instead of using sequelize

2022-10-20 11:02 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 21:01 UTC, Raghad-Mezied requested changes

2022-10-22 20:19 UTC, Raghad-Mezied approved these changes

2022-10-22 20:22 UTC, merged