Created the class feedback review.
CA-G12/GeekSchool pull request #67
Opened 2022-10-19 06:15 UTC by moustf

- Created the controller for getting feedback for a class.
- Created the query for getting feedback for a class.
- Added the tests for the get feedback route.

2022-10-19 13:16 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-20 07:29 UTC, Raghad-Mezied requested changes

2022-10-20 07:29 UTC, Raghad-Mezied commented on server/controllers/class/getFeedback.ts
> +    next(new CustomError(err.status, err.msg));
Again just pass the error here.

2022-10-21 11:56 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 20:50 UTC, Raghad-Mezied approved these changes

2022-10-21 21:03 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-22 20:46 UTC, Aaya-Elsharief approved these changes

2022-10-23 06:54 UTC, Bas-Shiekh approved these changes

2022-10-23 06:55 UTC, Raghad-Mezied approved these changes

2022-10-23 06:59 UTC, Aaya-Elsharief approved these changes

2022-10-23 07:00 UTC, mahmoudhammad309 approved these changes

2022-10-23 07:00 UTC, merged