Created remove student from class route.
CA-G12/GeekSchool pull request #68
Opened 2022-10-19 08:51 UTC by moustf

- Created deleteStudentFromClass controller.
- Created deleteStudent from a class query.
- Tested deleting a student from a class route.
- Removed nodemon.json file.
- Added --runInBand flag to package.json.
- Imported functions and exported them from index files.

2022-10-19 13:15 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-20 07:27 UTC, Raghad-Mezied requested changes

2022-10-20 07:27 UTC, Raghad-Mezied commented on server/routes/class.ts
> +classRouter.delete('/class/:classId/student/delete', userAuth, teacherAuth, deleteStudentFromARequest);
Don't add the method at the end of the endpoint, remove `delete`

2022-10-20 07:27 UTC, Raghad-Mezied commented on server/queries/class/deleteStudentQuery.ts
> +const deleteStudentQuery = async (classId: string, studentId: string) => {
Let it be more clear name, you are just removing a student from the class, and the same for your controller.

2022-10-20 07:27 UTC, Raghad-Mezied commented on server/queries/class/deleteStudentQuery.ts
> +  });
Why do you find before destroying?

2022-10-20 07:27 UTC, Raghad-Mezied commented on server/controllers/class/deleteStudentFromClass.ts
> +      next(new CustomError(400, 'Wrong data is inserted!'));
Why you are handling the validation error when you are not doing any validation?

2022-10-20 07:27 UTC, Raghad-Mezied commented on server/controllers/class/deleteStudentFromClass.ts
> +  }
If there is and status and msg for your error, then no need to customize it! for your controller, you will not get customized errors, and then you don't have a status or message.

2022-10-21 11:54 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 20:38 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-21 21:04 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-22 20:57 UTC, merged