60 create get students route in class
CA-G12/GeekSchool pull request #69
Opened 2022-10-19 13:12 UTC by Bas-Shiekh

2022-10-20 06:16 UTC, moustf commented on server/controllers/class/getClassStudents.ts
> +    const data = await getClassStudentsQuery(classId);
Try to throw an error if something happens and the data returned null, it happened to me!

2022-10-20 06:18 UTC, moustf submitted a review, later dismissed
Great job on your work, especially the query :clap::clap:

2022-10-20 07:14 UTC, Raghad-Mezied requested changes

2022-10-20 07:14 UTC, Raghad-Mezied commented on server/queries/class/getClassStudents.ts
> +    }],
You need the parent data too

2022-10-20 20:39 UTC, Raghad-Mezied approved these changes

2022-10-21 18:49 UTC, moustf approved these changes

2022-10-21 21:04 UTC, Aaya-Elsharief approved these changes

2022-10-21 21:04 UTC, merged