Created add new feedback route.
CA-G12/GeekSchool pull request #70
Opened 2022-10-19 15:50 UTC by moustf

- Created add a new feedback controller.
- Created add a new feedback query.
- Created add new feedback tests.
- Added some of the work we did in other pull requests in order for the logic to work.

2022-10-20 07:06 UTC, Raghad-Mezied requested changes

2022-10-20 07:06 UTC, Raghad-Mezied commented on server/controllers/class/addNewFeedback.ts
> +    }
Validate the body, and for the student id, you don't get it from the body.
We did all the auth middleware so we can check who did the action, so you can get the id from it.

2022-10-20 07:06 UTC, Raghad-Mezied commented on server/controllers/class/addNewFeedback.ts
> +    if (!addedFeedback) throw new CustomError(500, 'Error occurred while adding new feedback!');
Again this thrown by the query

2022-10-21 11:51 UTC, Bas-Shiekh commented on server/utils/validation/addNewFeedbackValidation.ts
> +  obj: { id: string | number, classId: string, feedback: string },
It is possible that if you create a new interface type  for feedback that's  will be better

2022-10-21 11:52 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 20:32 UTC, Raghad-Mezied approved these changes

2022-10-21 20:43 UTC, Raghad-Mezied approved these changes

2022-10-21 21:05 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-23 06:25 UTC, Bas-Shiekh approved these changes

2022-10-23 06:39 UTC, Raghad-Mezied approved these changes

2022-10-23 06:40 UTC, Aaya-Elsharief approved these changes

2022-10-23 06:40 UTC, Bas-Shiekh approved these changes

2022-10-23 06:41 UTC, mahmoudhammad309 approved these changes

2022-10-23 06:42 UTC, merged