Created add new assingment route.
CA-G12/GeekSchool pull request #73
Opened 2022-10-19 20:11 UTC by moustf

- Created add a new assignment controller.
- Created add a new assignment query.
- Created add new assignment tests.
- Added some of the work we did in other pull requests in order for the logic to work.

2022-10-20 06:59 UTC, Raghad-Mezied requested changes

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/controllers/class/addNewAssignment.ts
> +import CustomError from '../../utils/CustomError';
Import from the utils

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/routes/class.ts
> +classRouter.post('/:classId/assignment/add', userAuth, teacherAuth, addNewAssignment);
let the endpoint be just `/:classId/assignment`, without `add`

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/controllers/class/addNewAssignment.ts
> +    const { title, description } = req.body;
Validate both your body and id

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/controllers/class/addNewAssignment.ts
> +    if (!assignment) throw new CustomError(500, 'Error happen while creating the assignment!');
If there is an error in creating the assignment, then your query will throw an error and you will catch it in your catch.

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/controllers/class/addNewAssignment.ts
> +    res.status(201).json({ message: 'Assignment is created successfully!', data: assignment });
Rename message to msg

2022-10-20 06:59 UTC, Raghad-Mezied commented on server/controllers/class/addNewAssignment.ts
> +    }
This will be correct after you fix your code and add validation, but from what you are doing now there is no need for it.

2022-10-20 08:27 UTC, Raghad-Mezied approved these changes

2022-10-21 11:43 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-23 07:50 UTC, Bas-Shiekh approved these changes

2022-10-23 10:05 UTC, Raghad-Mezied approved these changes

2022-10-23 10:08 UTC, mahmoudhammad309 approved these changes

2022-10-23 10:16 UTC, Aaya-Elsharief approved these changes

2022-10-23 10:16 UTC, merged