get all student who submit tasks
CA-G12/GeekSchool pull request #74
Opened 2022-10-19 21:11 UTC by mahmoudhammad309

get all students who submit tasks
CLOSE:#30

2022-10-20 07:44 UTC, Raghad-Mezied requested changes

2022-10-20 07:44 UTC, Raghad-Mezied commented on server/controllers/class/getAllStudentHowSubmitTasks.ts
> +    const data:any = await getAllStudentWhoSubmitTasksQuery(assignmentId);
This controller should get both, those who submit the task and who do not, you can check your task in the HackMD.

2022-10-20 20:30 UTC, Raghad-Mezied approved these changes

2022-10-20 20:30 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 18:51 UTC, moustf submitted a review, later dismissed

2022-10-22 11:53 UTC, merged