54 get assignments
CA-G12/GeekSchool pull request #75
Opened 2022-10-20 07:42 UTC by Aaya-Elsharief

2022-10-20 08:35 UTC, Raghad-Mezied requested changes

2022-10-20 08:35 UTC, Raghad-Mezied commented on server/routes/class.ts
> +classRouter.get('/class/:classId/assignments/:studentId?', userAuth, studentAndTeacher, studentAssignment);
You will get the student id from the middleware, remove it

2022-10-20 08:35 UTC, Raghad-Mezied commented on server/controllers/class/studentAssignment.ts
> +const studentAssignment = async (req: CustomRequest, res: Response, next:NextFunction) => {
update the name, it's for both

2022-10-20 09:26 UTC, Raghad-Mezied requested changes

2022-10-20 09:26 UTC, Raghad-Mezied commented on server/middlewares/studentAndTeacher.ts
> +    req.user = user;
You already passed the `userAuth` middleware where we add user data, so no need for this.

2022-10-20 09:26 UTC, Raghad-Mezied commented on server/queries/class/teacherAssignmentQuery.ts
> +    },
If there is no condition then don't write it

2022-10-21 11:57 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-21 20:13 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-21 20:16 UTC, moustf approved these changes

2022-10-22 19:37 UTC, merged