Created add new test modal.
CA-G12/GeekSchool pull request #80
Opened 2022-10-21 23:05 UTC by moustf

- Created add new test modal.
- Styled the modal.
- Imported the modal in the app component.

2022-10-23 12:49 UTC, Bas-Shiekh submitted a review, later dismissed

2022-10-23 12:50 UTC, mahmoudhammad309 approved these changes

2022-10-23 12:55 UTC, Aaya-Elsharief submitted a review, later dismissed

2022-10-24 16:07 UTC, Raghad-Mezied requested changes

2022-10-24 16:07 UTC, Raghad-Mezied commented on client/src/components/ClassTests/AddTest/AddTest.tsx
> +        text: "Something went wrong!",
Add the error message you receive from the back

2022-10-24 16:07 UTC, Raghad-Mezied commented on client/src/components/ClassTests/AddTest/AddTest.tsx
> +      source.cancel();
Why are you canceling here? you have already done with your request

2022-10-24 16:07 UTC, Raghad-Mezied commented on client/src/components/ClassTests/AddTest/AddTest.tsx
> +      source.cancel();
Same here

2022-10-24 16:07 UTC, Raghad-Mezied commented on client/src/components/ClassTests/AddTest/AddTest.css
> +}
Don't do generic style

2022-10-25 12:07 UTC, Raghad-Mezied approved these changes

2022-10-25 12:08 UTC, merged